name: techtrends

namespace:
  name: sandbox
 
service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: binhcools/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

ports:
  containerPort: 3111

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

readinessProbe:
  httpGet:
    path: /healthz
    port: 3111

livenessProbe:
  httpGet:
    path: /healthz
    port: 3111