name: "TechTrends - Package with Docker"

# doc said pushed to master branch
##  After creating the GitHub Action verify it executes successfully when a new commit is pushed to the master branch.
## 
# but requirement said trigger on push
##  Trigger on every push to the main branch
on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./project/techtrends
          file: ./project/Dockerfile
          push: true
          tags: jasonwee/techtrends:latest